version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: "@bazel/typescript"
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.2.1
    - 3.2.2
    - 3.2.3
    - 3.3.0
  - dependency-name: "@bazel/ibazel"
    versions:
    - 0.14.0
    - 0.15.6
    - 0.15.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.31
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: wait-on
    versions:
    - 5.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: typescript
    versions:
    - 3.9.7
  - dependency-name: handlebars
    versions:
    - 4.7.6
